name: shopping_organizer
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  cloud_firestore: ^5.6.0
  cupertino_icons: ^1.0.8
  fake_cloud_firestore: ^3.1.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_crashlytics: ^4.2.0
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7
  firebase_storage_mocks: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.1.1
  flutter_localization: ^0.3.0
  flutter_svg: ^2.0.16
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_mobile_ads: ^5.2.0
  google_sign_in: ^6.2.2
  google_sign_in_mocks: ^0.3.0
  image_picker: ^1.1.2
  injectable: ^2.5.0
  injectable_generator: ^2.6.2
  intl: any
  json_annotation: ^4.8.1
  logger: ^2.5.0
  mocktail: ^1.0.4
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  provider: ^6.1.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
