name: shopping_organizer
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  flutter_localization: ^0.2.0
  intl: any
  go_router: ^13.1.0
  get_it: ^7.6.7
  injectable: ^2.3.2
  injectable_generator: ^2.4.2
  firebase_auth: ^4.16.0
  fpdart: ^1.1.0
  logger: ^2.1.0
  mocktail: ^1.0.3
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  bloc_test: ^9.1.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true