name: shopping_organizer
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  bloc: ^8.1.3
  bloc_test: ^9.1.6
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.2
  fake_cloud_firestore: ^2.4.8
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^14.7.20
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localization: ^0.2.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.1.0
  injectable: ^2.3.2
  injectable_generator: ^2.4.2
  intl: any
  json_annotation: ^4.8.1
  logger: ^2.1.0
  mocktail: ^1.0.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  provider: ^6.1.2

flutter:
  uses-material-design: true
  generate: true
