// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLIQp_H1e1fgp7PPcC5L2RhIUx6FLyGiM',
    appId: '1:742083963858:web:45fdee51afe6b44645760b',
    messagingSenderId: '742083963858',
    projectId: 'shopping-finanse',
    authDomain: 'shopping-finanse.firebaseapp.com',
    storageBucket: 'shopping-finanse.appspot.com',
    measurementId: 'G-LF9HQCPS0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0sLRJXduvs8qN-0XamfaP12fDPmCVn1I',
    appId: '1:742083963858:android:4c852edbd244af5345760b',
    messagingSenderId: '742083963858',
    projectId: 'shopping-finanse',
    storageBucket: 'shopping-finanse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClSSHV2CdYx8X4iR9hGcNScne57iMgWJo',
    appId: '1:742083963858:ios:8a0abb4d4885307345760b',
    messagingSenderId: '742083963858',
    projectId: 'shopping-finanse',
    storageBucket: 'shopping-finanse.appspot.com',
    iosBundleId: 'com.example.shoppingOrganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClSSHV2CdYx8X4iR9hGcNScne57iMgWJo',
    appId: '1:742083963858:ios:3e4763f1a09db4fa45760b',
    messagingSenderId: '742083963858',
    projectId: 'shopping-finanse',
    storageBucket: 'shopping-finanse.appspot.com',
    iosBundleId: 'com.example.shoppingOrganizer.RunnerTests',
  );
}
